{
  "name": "AI Productivity Tools",
  "url": "https://github.com/shona-cmd/AI-Powered-Productivity-Tools",
  "description": "A complete AI productivity tools bundle with writing assistant, task manager, business toolkit, and student tools.",
  "public": true,
  "redirect_urls": [
    "https://github.com/shona-cmd/AI-Powered-Productivity-Tools"
  ],
  "setup_url": "https://github.com/shona-cmd/AI-Powered-Productivity-Tools",
  "hook_attributes": {
    "url": "https://github.com/shona-cmd/AI-Powered-Productivity-Tools"
  },
  "permissions": {
    "contents": "read",
    "issues": "read",
    "pull_requests": "read"
  },
  "events": [
    "issues",
    "pull_request"
  ]
}
